### ISSUE TITLE
Cant do cargo run with 2.0.0 ethers

### ISSUE THREAD

**Issue by Haider-Ali-DS** [gakonst/ethers-rs#2258] opened 2023-03-13 18:45 UTC
**Description**

Doing cargo run with `ethers = "2.0.0"` as dependency returns abigen error

```
error[E0433]: failed to resolve: could not find `ethers` in the list of imported crates
 --> /Users/mp-haidera-pyse-403/.cargo/registry/src/github.com-1ecc6299db9ec823/ethers-contract-2.0.0/src/multicall/contract.rs:4:1
  |
4 | abigen!(Multicall3, "src/multicall/multicall_abi.json");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `ethers` in the list of imported crates
  |
  = note: this error originates in the macro `abigen` (in Nightly builds, run with -Z macro-backtrace for more info)

error: cannot find attribute `ethcall` in this scope
 --> /Users/mp-haidera-pyse-403/.cargo/registry/src/github.com-1ecc6299db9ec823/ethers-contract-2.0.0/src/multicall/contract.rs:4:1
  |
4 | abigen!(Multicall3, "src/multicall/multicall_abi.json");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this error originates in the macro `abigen` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `ethers` in the list of imported crates
 --> /Users/mp-haidera-pyse-403/.cargo/registry/src/github.com-1ecc6299db9ec823/ethers-contract-2.0.0/src/multicall/contract.rs:4:1
  |
4 | abigen!(Multicall3, "src/multicall/multicall_abi.json");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `ethers` in the list of imported crates
  |
  = help: consider importing one of these items:
          crate::Lazy
          futures_util::future::Lazy
          once_cell::sync::Lazy
          once_cell::unsync::Lazy
  = note: this error originates in the macro `abigen` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `ethers` in the list of imported crates
 --> /Users/mp-haidera-pyse-403/.cargo/registry/src/github.com-1ecc6299db9ec823/ethers-contract-2.0.0/src/multicall/contract.rs:4:1
  |
4 | abigen!(Multicall3, "src/multicall/multicall_abi.json");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `ethers` in the list of imported crates
  |
  = help: consider importing one of these items:
          crate::Contract
          ethers_core::abi::Contract
  = note: this error originates in the macro `abigen` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `ethers` in the list of imported crates
 --> /Users/mp-haidera-pyse-403/.cargo/registry/src/github.com-1ecc6299db9ec823/ethers-contract-2.0.0/src/multicall/contract.rs:4:1
  |
4 | abigen!(Multicall3, "src/multicall/multicall_abi.json");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `ethers` in the list of imported crates
  |
  = help: consider importing this trait:
          ethers_core::abi::AbiEncode
  = note: this error originates in the macro `abigen` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0433`.
error: could not compile `ethers-contract` due to 5 previous errors
warning: build failed, waiting for other jobs to finish...
```

How to produce error:
1. created a new project. `cargo new project_name`
2. added ethers="2.0.0" in dependency 
3. Ran cargo run.
4. error produced.

**Comment by mattsse** [comment] 2023-03-13 19:08
can reproduce.

did we fix this on master yet @DaniPopes

**Comment by mattsse** [comment] 2023-03-13 19:37
seems to be fixed on master

```
ethers = { git = "https://github.com/gakonst/ethers-rs" }
```

**Comment by Haider-Ali-DS** [comment] 2023-03-13 19:58
yeah, can confirm it's fixed on the master branch. Thanks for informing me. Will be waiting for the next release.

**Closed** 2023-03-13 19:58 UTC
Labels: bug

**Comment by DaniPopes** [comment] 2023-03-13 23:07
weird, can't reproduce on either stable or nightly, with `cargo add ethers`
