### ISSUE TITLE
abigen is intolerant of duplicate names with different casing

### ISSUE THREAD

**Issue by casualjim** [gakonst/ethers-rs#571] opened 2021-11-11 08:28 UTC
**Version**
https://github.com/gakonst/ethers-rs#906c504f

**Platform**
linux

**Description**
Abigen is intolerant of identifiers that have the same name but differ in casing.

For example the names `index` and `INDEX` both appear in the sOHM contract: 0x04f2694c8fcee23e8fd0dfea1d4f5bb8c352111f

I tried this code:

```rust
Abigen::new(
    "StakedOHM",
    "https://etherscan.io/address/0x04f2694c8fcee23e8fd0dfea1d4f5bb8c352111f",
  )
  .unwrap()
  .generate()
  .unwrap()
  .write_to_file("src/contracts/staked_ohm.rs")
  .unwrap();
```

I expected to see this happen: the generated code compiles

Instead, this happened: 

```
error[E0201]: duplicate definitions with name `index`:
   --> src/contracts/staked_ohm.rs:153:5
    |
51  | /     pub fn index(&self) -> ethers::contract::builders::ContractCall<M, ethers::core::types::U256> {
52  | |       self
53  | |         .0
54  | |         .method_hash([45, 247, 92, 177], ())
55  | |         .expect("method not found (this should never happen)")
56  | |     }
    | |_____- previous definition of `index` here
...
153 | /     pub fn index(&self) -> ethers::contract::builders::ContractCall<M, ethers::core::types::U256> {
154 | |       self
155 | |         .0
156 | |         .method_hash([41, 134, 192, 229], ())
157 | |         .expect("method not found (this should never happen)")
158 | |     }
    | |_____^ duplicate definition
```

**Comment by mattsse** [comment] 2021-11-11 09:28
Nice catch, this is similar to #548 and should be fixed with the same approach.

In the meantime, you should be able to prevent this with `methods` field like

```rust
abigen!(StakedOHM,
    "https://etherscan.io/address/0x04f2694c8fcee23e8fd0dfea1d4f5bb8c352111f",
    methods {
        INDEX() as index_;
    }
);
```

**Comment by gakonst** [comment] 2021-12-05 20:37
@casualjim could you please check that the issue is no longer present in master?

**Closed** 2021-12-05 20:36 UTC
Labels: bug

**Comment by casualjim** [comment] 2021-12-06 05:04
There is progress: different error, but still an issue:

```
error[E0428]: the name `IndexCall` is defined multiple times
 --> src/contracts/ethereum/mod.rs:3:3
  |
3 | /   abigen!(
4 | |     StakedOHM,
5 | |     "./abi/staked_ohm.json",
6 | |     event_derives(serde::Deserialize, serde::Serialize)
7 | |   );
  | |    ^
  | |    |
  | |____`IndexCall` redefined here
  |      previous definition of the type `IndexCall` here
  |
  = note: `IndexCall` must be defined only once in the type namespace of this module
  = note: this error originates in the macro `abigen` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0428]: the name `Index` is defined multiple times
 --> src/contracts/ethereum/mod.rs:3:3
  |
3 | /   abigen!(
4 | |     StakedOHM,
5 | |     "./abi/staked_ohm.json",
6 | |     event_derives(serde::Deserialize, serde::Serialize)
7 | |   );
  | |    ^
  | |    |
  | |____`Index` redefined here
  |      previous definition of the type `Index` here
  |
  = note: `Index` must be defined only once in the type namespace of this enum
  = note: this error originates in the macro `abigen` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by mattsse** [comment] 2021-12-06 10:39
@casualjim 
hmm, could not reproduce with master, as

```rust
    abigen!(
        StakedOHM,
        "etherscan:0x04f2694c8fcee23e8fd0dfea1d4f5bb8c352111f"
    );
```

compiles and generates

```rust
fn index()
fn INDEX()
```

**Comment by gakonst** [comment] 2021-12-06 12:47
@casualjim what's the exact ABI you're using?

**Comment by casualjim** [comment] 2021-12-06 17:14
I did  update to master, I verified the commit hashes after running `cargo update`

I think maybe some local cache needed to be invalidated.  

It works now!  And it appears that the etherscan stuff now also works again.

**Comment by casualjim** [comment] 2021-12-06 17:19
> @casualjim what's the exact ABI you're using?

I used a downloaded version, because when I was trying this there was an issue with downloading from etherscan through ethers.

I used a json structure like this: 

```json
[
  {
    "network": "ethereum",
    "symbol": "sOHM",
    "typeName": "StakedOHM",
    "filename": "staked_ohm",
    "address": "0x04f2694c8fcee23e8fd0dfea1d4f5bb8c352111f"
  },
]
```
  
in combination with this download script:

```sh
set -eu -o pipefail

declare -A explorers=( ["ethereum"]="etherscan.io" ["polygon"]="polygonscan.com" ["avalanche"]="snowtrace.io" )
declare -A apikeys=( ["ethereum"]="$ETHERSCAN_API_KEY" ["polygon"]="$POLYGONSCAN_API_KEY" ["avalanche"]="$SNOWTRACE_API_KEY" )

download::abi() {
  local explorer
  local filename
  local address
  local network

  network="$(jq -r .network <<< "$1")"
  explorer="${explorers[$network]}"
  address="$(jq -r .address <<< "$1")"
  filename="$(jq -r .filename <<< "$1")"

  >&2 echo "downloading $(jq -r .typeName <<< "$1") $(jq -r .network <<< "$1") ABI"

  url="https://api.${explorer}/api?"
  url="${url}module=contract&action=getabi"
  url="${url}&address=${address}"
  url="${url}&apikey=${apikeys[$network]}"
  curl -LSs "${url}" | jq -r .result | jq > "abi/${filename}.json"
}

main() {
  readarray -t contracts < <(jq -c '.[]' ./contractdeps.json)
  for item in "${contracts[@]}"; do
    download::abi "$item"
  done
}

main "$@"
```
