### ISSUE TITLE
Support `FixedArray` with larger than 32 elements in `abigen!`

### ISSUE THREAD

**Issue by k-huetsch** [gakonst/ethers-rs#1640] opened 2022-08-29 12:54 UTC
**Is your feature request related to a problem? Please describe.**
Rust does not implement the `Default` for `[T; N]` where `N` > 32.  So if a solidity function has an input parameter with type `uint256[40]`, `abigen!` can not work well. 

**Describe the solution you'd like**
Introduce a custom trait `CustomDefault`, which has the same behavior as the `Default` trait, except the way to initialize an array `[T; N]`. It simply assumes `T: Clone` and initializes `[T; N]` by `[T::custom_default(); N]`. Then implement `Default` for solidity structs/inputs by `CustomDefault`.

**Describe alternatives you've considered**

**Alternative 1:**
Manually implementing the `Default` trait in the procedure macro. 

**Alternative 2:**
Use a wrapped type for large fixed arrays. Like what you did for `Uint8`.

**Comment by mattsse** [comment] 2022-08-29 13:07
this should probably be handled with alternative 1

same goes for PartialEq and Eq

this means we need to track whether to manually impl default for (call)structs

**Comment by mlagoma** [comment] 2022-08-29 20:44
I'm hitting a similar `the trait ``___`` is not implemented for` problem with Defaults/PartialEq/Eq when I have more than 12 outputs (components) ("parameters") on a solidity function.
Could this be related?

**Comment by mattsse** [comment] 2022-08-29 21:05
what's the trait that's missing?

**Comment by mlagoma** [comment] 2022-08-29 21:20
I think Default, PartialEq, Eq, and also Debug.

Below is the log (I've replaced actual types with `[More than 12 types]`).
If there are only 12 types then it works. These are from the abi for a solidity function under `"outputs": [ "components": [` 

```
error[E0277]: `([More than 12 types])` doesn't implement `Debug`
 --> src/main.rs:5:1
  |
5 | / abigen!(Contract,
6 | |     "abi/Contract.json",);
  | |___________________________________^ `([More than 12 types])` cannot be formatted using `{:?}` because it doesn't implement `Debug`
  |
  = help: the trait `Debug` is not implemented for `([More than 12 types])`
  = help: the following other types implement trait `Debug`:
            ()
            (A, Z, Y, X, W, V, U, T)
            (B, A, Z, Y, X, W, V, U, T)
            (C, B, A, Z, Y, X, W, V, U, T)
            (D, C, B, A, Z, Y, X, W, V, U, T)
            (E, D, C, B, A, Z, Y, X, W, V, U, T)
            (T,)
            (U, T)
          and 5 others
  = note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `([More than 12 types]): Default` is not satisfied
 --> src/main.rs:5:1
  |
5 | / abigen!(Contract,
6 | |     "abi/Contract.json",);
  | |___________________________________^ the trait `Default` is not implemented for `([More than 12 types])`
  |
  = help: the following other types implement trait `Default`:
            ()
            (A, Z, Y, X, W, V, U, T)
            (B, A, Z, Y, X, W, V, U, T)
            (C, B, A, Z, Y, X, W, V, U, T)
            (D, C, B, A, Z, Y, X, W, V, U, T)
            (E, D, C, B, A, Z, Y, X, W, V, U, T)
            (T,)
            (U, T)
          and 5 others
  = note: this error originates in the derive macro `Default` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `([More than 12 types]): Eq` is not satisfied
 --> src/main.rs:5:1
  |
5 | / abigen!(Contract,
6 | |     "abi/Contract.json",);
  | |___________________________________^ the trait `Eq` is not implemented for `([More than 12 types])`
  |
  = help: the following other types implement trait `Eq`:
            ()
            (A, Z, Y, X, W, V, U, T)
            (B, A, Z, Y, X, W, V, U, T)
            (C, B, A, Z, Y, X, W, V, U, T)
            (D, C, B, A, Z, Y, X, W, V, U, T)
            (E, D, C, B, A, Z, Y, X, W, V, U, T)
            (T,)
            (U, T)
          and 5 others
note: required by a bound in `AssertParamIsEq`
  = note: this error originates in the derive macro `Eq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0369]: binary operation `==` cannot be applied to type `([More than 12 types])`
 --> src/main.rs:5:1
  |
5 | / abigen!(Contract,
6 | |     "abi/Contract.json",);
  | |___________________________________^
  |
  = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0369]: binary operation `!=` cannot be applied to type `([More than 12 types])`
 --> src/main.rs:5:1
  |
5 | / abigen!(Contract,
6 | |     "abi/Contract.json",);
  | |___________________________________^
  |
  = note: this error originates in the derive macro `PartialEq` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0277, E0369.
For more information about an error, try `rustc --explain E0277`.
```

**Comment by mattsse** [comment] 2022-08-29 21:23
could you share the abi if possible so I can work on a fix: derive manually if too large

**Comment by mlagoma** [comment] 2022-08-29 21:30
Posted a contract to reproduce below. Works as is with one of the outputX deleted.
Apologies if this issue is derailed, thought it could possibly be related.

```
[
  {
    "inputs": [
      {
        "internalType": "uint160",
        "name": "input",
        "type": "uint160"
      }
    ],
    "name": "doSomething",
    "outputs": [
      {
        "components": [
          {
            "internalType": "bytes",
            "name": "output1",
            "type": "bytes"
          },
          {
            "internalType": "bytes",
            "name": "output2",
            "type": "bytes"
          },
          {
            "internalType": "bytes",
            "name": "output3",
            "type": "bytes"
          },
          {
            "internalType": "bytes",
            "name": "output4",
            "type": "bytes"
          },
          {
            "internalType": "bytes",
            "name": "output5",
            "type": "bytes"
          },
          {
            "internalType": "bytes",
            "name": "output6",
            "type": "bytes"
          },
          {
            "internalType": "bytes",
            "name": "output7",
            "type": "bytes"
          },
          {
            "internalType": "bytes",
            "name": "output8",
            "type": "bytes"
          },
          {
            "internalType": "bytes",
            "name": "output9",
            "type": "bytes"
          },
          {
            "internalType": "bytes",
            "name": "output10",
            "type": "bytes"
          },
          {
            "internalType": "bytes",
            "name": "output11",
            "type": "bytes"
          },
          {
            "internalType": "bytes",
            "name": "output12",
            "type": "bytes"
          }
        ],
        "internalType": "struct Contract.Response",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
]
```

**Comment by mattsse** [comment] 2022-08-29 21:39
thanks, that's the same problem, we should either skip the derives for large structs or implement them manually, wdyt @gakonst

**Comment by gakonst** [comment] 2022-08-29 22:01
Meh I really hope we find some const-generic type solution? I think we keep implementing them manually.

**Comment by mattsse** [comment] 2022-08-29 23:10
just tried it and it succeeded https://github.com/gakonst/ethers-rs/pull/1642

what's your rust version, could be that you's is outdated, unsure when this has been added.

derives for large tuples seem to work:

**Comment by mlagoma** [comment] 2022-08-30 00:49
Looks like it matches the test env #1642 :
```
$ rustup -V
rustup 1.25.1 (bb60b1e89 2022-07-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.63.0 (4b91a6ea7 2022-08-08)`

**Comment by mlagoma** [comment] 2022-08-30 01:14
Changed my Cargo.toml to point to the latest ethers master and it's working. Cool!
I can use this as a workaround for now. I suppose something fixes my issue that will be resolved in the next release.

**Comment by gakonst** [comment] 2022-08-30 03:09
Sounds great!

**Comment by k-huetsch** [comment] 2022-08-30 07:56
@gakonst Kindly remind that this issue is opened for a large fixed array, instead of a large tuple. Since the original discussion is still unsolved, would you like to reopen this issue?

**Comment by k-huetsch** [comment] 2022-08-30 08:07
> this should probably be handled with alternative 1
> 
> same goes for PartialEq and Eq
> 
> this means we need to track whether to manually impl default for (call)structs

@mattsse 

`Default` is the only trait that supports the fixed array with <= 32 elements, but does not support larger fixed arrays. The other traits like `PartialEq` work well for a large fixed array. [Primitive type array in std doc.](https://doc.rust-lang.org/std/primitive.array.html)

So, my first proposal is hacking with the `Default` trait, instead of large fixed array.

**Comment by gakonst** [comment] 2022-08-30 17:53
> @gakonst Kindly remind that this issue is opened for a large fixed array, instead of a large tuple. Since the original discussion is still unsolved, would you like to reopen this issue?

Oh sorry - your repro I think was with a tuple? Mind giving an ABI repro for your edge case?

**Comment by k-huetsch** [comment] 2022-08-31 09:24
Thanks!

[This file](https://github.com/k-huetsch/ethers-rs/blob/ionian-dev/ethers-contract/tests/solidity-contracts/LargeFixedArray.json) gives a simple example of this issue. 

> **Describe the solution you'd like** Introduce a custom trait `CustomDefault`, which has the same behavior as the `Default` trait, except the way to initialize an array `[T; N]`. It simply assumes `T: Clone` and initializes `[T; N]` by `[T::custom_default(); N]`. Then implement `Default` for solidity structs/inputs by `CustomDefault`.

[This commit](https://github.com/k-huetsch/ethers-rs/commit/c35d1e0514aec5be3a56d567b0bbf823a5055220)  implements my proposed solution. It fulfills my need. But I'm not sure if it is backward compatible with all the cases, since I'm not very familiar with the code base.

**Closed** 2022-08-31 15:24 UTC

**Comment by k-huetsch** [comment] 2022-09-01 04:06
Thanks. 

Yes, I agree with that. A helper trait is an ad-hoc fix for specific usages. But it is not a good idea for a general tool. Because all the subsequent changes must be aware of this helper trait.
